# Configuração SMTP

quarkus.mailer.from=kethelenvictoria2016@gmail.com
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.username=kethelenvictoria2016@gmail.com
quarkus.mailer.password="senha gerada pelo gmail"
quarkus.mailer.ssl=false   
quarkus.mailer.start-tls=OPTIONAL
quarkus.mailer.mock=false