quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = mail
quarkus.datasource.password = 123456
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/maildb

%prod.quarkus.hibernate-orm.database.generation=update
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql = false

mp.jwt.verify.publickey.location = token/chave_publica.pem
mp.jwt.verify.issuer=mail-jwt
smallrye.jwt.sign.key.location=token/chave_privada.pem

# Configuração SMTP
quarkus.mailer.from=kethelenvictoria2016@gmail.com
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.username=kethelenvictoria2016@gmail.com
quarkus.mailer.password="Sua chave de acesso" o gmail fornece uma chave de acesso 
quarkus.mailer.ssl=false   
quarkus.mailer.start-tls=OPTIONAL
quarkus.mailer.mock=false

#configuracao de LOG
quarkus.log.level = INFO
quarkus.log.category."br.unitins.topicos1".level = TRACE

#configuracao do console log
quarkus.log.console.color = true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t)  %s%e%n
quarkus.log.console.level = DEBUG

#configuracao do log em arquivos
quarkus.log.file.enable=true
quarkus.log.file.path=/tmp/log_tp1_2024.log
quarkus.log.file.level=DEBUG
quarkus.log.file.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t)  %s%e%n
quarkus.log.file.rotation.file-suffix=.dd-MM-yyyy-HH-mm

# CORS (sem alterações)
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,PUT,POST,DELETE,PATCH
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with,origin
quarkus.http.cors.exposed-headers=Authorization,Location
quarkus.http.cors.access-control-max-age=24H
quarkus.http.cors.access-control-allow-credentials=true

quarkus.devservices.enabled=false
quarkus.analytics.disabled=true

# OpenAPI + Swagger
quarkus.smallrye-openapi.security-scheme=jwt
quarkus.smallrye-openapi.security-scheme.BearerAuth.type=http
quarkus.smallrye-openapi.security-scheme.BearerAuth.scheme=bearer
quarkus.smallrye-openapi.security-scheme.BearerAuth.bearer-format=JWT
quarkus.smallrye-openapi.security-requirements=BearerAuth

# Keycloak OIDC (para Quarkus proteger seus endpoints)
quarkus.oidc.auth-server-url=http://localhost:8180/realms/MeuRealm
quarkus.oidc.client-id=EnvioEmailApp
quarkus.oidc.credentials.secret=iTt1WjbjUdqroYNN4a0yr1jFRyqs4H23
quarkus.oidc.application-type=service
quarkus.oidc.roles.source=accesstoken           

# Quem pode chamar o quê
quarkus.http.auth.permission.public.paths=/api/auth/*,/q/swagger-ui/*,/q/openapi
quarkus.http.auth.permission.public.policy=permit

quarkus.http.auth.permission.secure.paths=/api/*
quarkus.http.auth.permission.secure.policy=authenticated

# REST Client Keycloak (para suas chamadas administrativas via MP Rest Client)
quarkus.rest-client.keycloak-api.url=http://localhost:8180
quarkus.rest-client.keycloak-api.scope=javax.inject.Singleton
quarkus.rest-client.keycloak-api.connect-timeout=5000
quarkus.rest-client.keycloak-api.read-timeout=10000

keycloak.server-url=http://localhost:8180
keycloak.realm=MeuRealm
keycloak.client-id=EnvioEmailApp
keycloak.client-secret=iTt1WjbjUdqroYNN4a0yr1jFRyqs4H23

keycloak-api/mp-rest/url=http://localhost:8180